In [1]:
import geopandas
import pandas as pd
import numpy as np
from shapely.ops import unary_union

In [2]:
df.head()

NameError: name 'df' is not defined

In [3]:
df = pd.read_csv("../data/cook_county_with_geometries2.csv")

In [4]:
len(df)

12285

In [5]:
len(df[df['geometry'].isnull()])

4177

In [8]:
len(df[(df['geometry'].isnull()) & (df['Range'].isnull()) & ~(df['Aliquot Parts or Lot'].str.contains("OT"))])

435

In [7]:
len(df[df['Aliquot Parts or Lot'].str.contains("OT")])

2645

In [17]:
gdf = geopandas.read_file("../data/lots.geojson")

In [28]:
df[df['geometry'].notnull()]

,Unnamed: 0.1,Unnamed: 0,Cleaned Name,Purchaser,Residence,Social Status,Aliquot Parts or Lot,Section Number,Township,Range,...,Volume,Page,Shapefile Object ID,Voided,Lot Matches,Name Matches,Duplicate,IBL,part,geometry
159,159,161,ANDREWS DAVID,ANDREWS DAVID,UNKNOWN,NaN,NWFRNIBL,5.0,36N,14E,...,687,246,8300.0,False,NaN,157;158;159;160;161;162;163;164;165;166;167,False,NIBL,NW,POLYGON ((-87.65407432326833 41.64385159997570...
181,181,183,ANDREWS WILLIAM,ANDREWS WILLIAM,UNKNOWN,NaN,NFRSENIBL,28.0,36N,13E,...,687,172,9000.0,False,NaN,173;174;175;176;177;178;179;180;181;182;183;18...,False,NIBL,NSE,POLYGON ((-87.74055941030262 41.57769623587411...
188,188,190,ANDREWS WILLIAM,ANDREWS WILLIAM,UNKNOWN,NaN,SEFRNIBL,6.0,36N,14E,...,687,247,8259.0,False,NaN,173;174;175;176;177;178;179;180;181;182;183;18...,False,NIBL,SE,POLYGON ((-87.66293458935905 41.63712292024054...
1131,1131,1139,BRAND MICHEL,BRAND MICHEL,UNKNOWN,NaN,NWSWNIBL,32.0,36N,13E,...,791,83,9034.0,False,NaN,1138;1139,False,NIBL,NWSW,POLYGON ((-87.77426412508116 41.56609365418929...
1453,1453,1469,BUNN JOHN W,BUNN JOHN W,UNKNOWN,NaN,SWFRNIBL,7.0,37N,15E,...,66,210,7530.0,False,1469,1468;1469;1470,False,NIBL,SW,"POLYGON ((-87.5597501374619 41.71335232516838,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11695,11695,12670,WERNER GOTTLIEB,WERNER GOTTLIEB,UNKNOWN,NaN,SWSWNIBL,6.0,35N,13E,...,791,220,9198.0,False,NaN,12670,False,NIBL,SWSW,POLYGON ((-87.79231101522777 41.54411077832968...
11934,11934,12913,WILLE HENRY,WILLE HENRY,UNKNOWN,NaN,NESESIBL,32.0,36N,13E,...,791,71,9034.0,False,NaN,12912;12913;12914;12915,False,SIBL,NESE,POLYGON ((-87.75249100744672 41.56437201974883...
11935,11935,12914,WILLE HENRY,WILLE HENRY,UNKNOWN,NaN,NWSESIBL,32.0,36N,13E,...,791,61,9034.0,False,NaN,12912;12913;12914;12915,False,SIBL,NWSE,POLYGON ((-87.76224573622063 41.56116293452383...
12129,12129,13111,WITTE WILHELM,WITTE WILHELM,UNKNOWN,NaN,SWSESIBL,6.0,36N,14E,...,791,344,8259.0,False,NaN,13111;13112,False,SIBL,SWSE,POLYGON ((-87.66578533442173 41.63350403880781...
12131,12131,13113,WITTE WILLIAM JR,WITTE WILLIAM JR,UNKNOWN,NaN,SWFRSIBL,6.0,36N,14E,...,793,370,8259.0,False,NaN,13113,False,SIBL,SW,POLYGON ((-87.66573056954695 41.62988515737508...